added login page
mcsp-blue-ocean/quest pull request #70
Opened 2023-12-20 20:46 UTC by mnorthup28

When you click on the login icon the page now renders a login screen with a submit button.

2023-12-20 22:02 UTC, shannonscotta commented
leaving for @gnprwx since he's UI owner ❤️

2023-12-21 16:47 UTC, gnprwx requested changes

2023-12-21 16:47 UTC, gnprwx commented on client/src/App.jsx
>        <Landing />
<Header> should be strictly rendered in App and decoupled from Landing.

2023-12-21 16:47 UTC, gnprwx commented on client/src/Landing.jsx
> +      <Header onToggleModal={handleToggleModal} />
Header should not be rendered from within Landing. Reset to where Header is rendered in App (as is originally done) and have the modal code be moved to to Header component or somewhere else where it's independent or the context makes sense. 

That is, you want an image inside Header to render the modal, so the code could make sense in header. Or try it out in App to where Modal is rendered under Header from there.

Landing has nothing to do with logging in, and with the additional pages being added soon, you'd end up repeating this code.

2023-12-21 22:00 UTC, closed without merging